---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# runningEmu

<!-- badges: start -->
<!-- badges: end -->

```{r}
library(runningEmu)
```

The goal of runningEmu is to create an environment for a Hacky Hour competition

## Example

There are 3 functions to be optimized in this package.

Below are the runtimes for one evaluation of these functions

```{r}
bigM <- 1e6
m <- matrix(rnorm(bigM), nrow=as.integer(sqrt(bigM)))
bench::system_time(un(m))
v <- sample(1:10, bigM, replace=TRUE)
bench::system_time(deux(v))
vv <- sample(1:10, bigM, replace=TRUE, prob=sample(seq(0.1,0.9,by=0.1), 10, replace = TRUE))
bench::system_time(trois(vv))
```

And here are the runtimes for 50 evaluations of these functions.

```{r}
bench::mark(un(m), iterations = 10)
bench::mark(deux(v), iterations = 10)
bench::mark(trois(vv), iterations = 10)
```